# Start from the official Ubuntu base image
FROM ubuntu:latest

# Prevent apt-get from asking for user input
ENV DEBIAN_FRONTEND=noninteractive

# Update package database and get dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y sudo curl

# Create a new user 'tim', set their shell to bash, and add them to the 'sudo' group
RUN useradd -m -s /bin/bash -G sudo tim

# Set the password for 'tim' non-interactively.
RUN echo 'tim:1234' | chpasswd

# Allow users in the 'sudo' group to use sudo without a password prompt
RUN echo '%sudo ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers

# Switch the context to the new user
USER tim
WORKDIR /home/tim

# Set the default command to a bash shell
CMD ["/bin/bash"]
