[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
offset = { x = 1, y = 0 }

[terminal]
shell = "nu"

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" },
    { mouse = "Right", action = "ClearSelection" },
]

[cursor.style]
shape = "Block"
blinking = "On"

[selection]
save_to_clipboard = true

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"

[colors.selection]
text = "CellForeground"
background = "#504945"

[colors.search]
matches = { foreground = "#282828", background = "#a89984" }
focused_match = { foreground = "#282828", background = "#fe8019" }

[colors.hints]
start = { foreground = "#282828", background = "#fabd2f" }
end = { foreground = "#282828", background = "#a89984" }

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fbf1c7"

[colors.dim]
black = "#32302f"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#928374"

# Indexed colors for Orange which are also provided by gruvbox.
[[colors.indexed_colors]]
index = 16
color = "#d65d0e" # neutral_orange

[[colors.indexed_colors]]
index = 17
color = "#fe8019" # bright_orange