directory: D:\Music

# may have to make this parent dir if it does not exist?
library: D:\State\beets\library.db
statefile: D:\State\beets\state.pickle

plugins: fetchart lastgenre fromfilename missing badfiles
# make sure to install these dependencies for these plugins
# - requests
# - pylast
# (can put them in the pipx venv via `pipx runpip beets install requests pylast`)

paths:
    default: $albumartist/$album ($original_year)/$track - $title

badfiles:
    check_on_import: yes
    # the syntax for these commands is limited. will put the file as the last arg no matter what
    # i just really want this for missing file checks, not integrity checks, so no-op.
    commands:
        ogg: python --version
        opus: python --version
        flac: python --version
        m4a: python --version