# ripgrep configuration
# Reference: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file

# Note: ripgrep will read a configuration file iff the RIPGREP_CONFIG_PATH
# environment variable is set to the path of one.

# search hidden files / directories (e.g. dotfiles) by default
--hidden

# search case-insensitively if the pattern is all lowercase
--smart-case

# use the "kitty" hyperlink format for clickable links in the terminal
--hyperlink-format kitty
