"$schema" = 'https://starship.rs/config-schema.json'

format = """$username@$hostname $os $git_branch$git_state$git_status
$directory \\($status $cmd_duration\\) """

[username]
style_user = "fg:#e377c2 bold"
style_root = "fg:#d62728 bold"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
style = "fg:#e377c2 bold"
format =  "[$hostname]($style)"
trim_at = ""

[time]
disabled = false
format = "[$time]($style)"
time_format = "%Y-%m-%dT%H:%M:%S%:z"
style = "white"

[git_branch]
format = "[$branch]($style)"
style = "fg:#ff7f0e bold"

[git_state]
format = ':[$state]($style)'
style = "fg:#ff7f0e bold"

[git_status]
format = ':[$all_status]($style)'
style = "fg:#ff7f0e bold"

[directory]
format = '[$path]($style)'
style = "fg:#1f77b4 bold underline"
truncate_to_repo = false
truncation_length = 0

[status]
# it always stays on success for powershell currently:
# https://github.com/starship/starship/issues/4299
symbol = "[✘](bold fg:#d62728) "
success_symbol = "[✓](bold fg:#2ca02c)"
format = '[$symbol$common_meaning$signal_name$maybe_int]($style)'
map_symbol = true
disabled = false

[cmd_duration]
min_time = 0
format = '[$duration]($style)'
style = "fg:#bcbd22"

[os]
format = "on [($type)]($style)"
style = "bold fg:#7f7f7f"
disabled = false